# Generated by Django 6.0.6 on 2026-07-04 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_leaverequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leavebalance',
            options={'ordering': ('-year', 'leave_type_id')},
        ),
        migrations.AlterModelOptions(
            name='leaverequest',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='leavetype',
            options={'ordering': ('name',)},
        ),
    ]
